### ISSUE TITLE
Higher-Order Boundary Conditions - Part 1

### ISSUE THREAD

**Issue by cortner** [cortner/MaterialsScienceTools.jl#11]
CC @thudso @jjbraun 

I want to use this issue to discuss anything coming up in the implementation for the next paper. 

## TODO 

- [x] Linear elasticity solutions: I believe Tom has finished this, all tests pass ok
- [x] CLE Dislocation predictor: I believe this is not yet running correctly, tentatively assigning this to Tom?
- [x] Cauchy-Born: done 
- [x] PDE solver to solve at least for the next-order corrector 
- [ ] Atomistic Green's Function 
- [ ] Computation and convergence test for the dipole tensor 
- [ ] Implementation of the predictor-corrector iteration for point defects
- [ ] Implementation of the predictor-corrector iteration for screw dislocations

Am I missing anything?

**Comment by cortner** [comment]
@thudso  @jjbraun can either of you remind me whether we actually need the Lattice Green's function in a first instance? I can't quite remember what the conclusion was.

**Comment by thudso** [comment]
CLE dislocation predictors are running fine (tests pass); I don't think you're missing anything. If I remember right, I think we can do without the atomistic Green's function, but then we do definitely need to solve the PDE (but @jjbraun can confirm!).

**Comment by cortner** [comment]
so are you saying you are actually getting the correct decay rates for the forces?

**Comment by thudso** [comment]
Ah, sorry; I had forgotten about this issue. I will look into it.

On 9 Mar 2018, at 20:58, Christoph Ortner <notifications@github.com<mailto:notifications@github.com>> wrote:


so are you saying you are actually getting the correct decay rates for the forces?

**Comment by cortner** [comment]
<img width="609" alt="error-c1" src="https://user-images.githubusercontent.com/7688515/37254052-b7463b72-2531-11e8-9c09-4ef540e8d255.png">

This shows the convergence of the dipole tensor for a vacancy in a Lennard-Jones FCC material. @jjbraun does this match your result? If not, what are possible reasons? (e.g. I didn't pre-relax, i.e. the reference crystal is not stress-free, could this be a problem?)
